require:
  - rubocop-rails
inherit_from:
  - node_modules/@prettier/plugin-ruby/rubocop.yml
inherit_mode:
  merge:
    - Include
    - Exclude
AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  Exclude:
    - test/dummy/**/*
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
Documentation:
  Enabled: false
